0000 MSSWIN32 - Mahogany Storage Server v4.0
0001 MSSLIN32 - Mahogany Storage Server v4.0
0002 Exception %2 occurred on share %3
0003 Unhandled SCSI CDB: %2
0004 Unable to instantiate storage server
0005 Failed to create storage processing thread: %2
0006 Invalid share path string
0007 Could not open device: %2
0008 Failed to lock device for writing: %2
0009 Error getting device stat: %2
0011 Device is invalid to read
0012 Error seeking to location: %2
0013 Eror reading device: %2
0014 Required amount was not read
0015 Device is invalid to write
0017 Error writing to device: %2
0018 Error synchronizing data on %2
0019 Device is invalid
0020 Required amount of data was not read
0021 %2 of %3 bytes read
0022 %2 of %3 bytes written
0023 %2 of %3 bytes transferred
0024 Device %2
0025 Memory allocation error
0026 Unable to start socket connection: %2
0027 Path to device not specified
0028 Unknown device type encountered
0029 Socket error: %2
 

